### PR TITLE
Cleaned up paths, arguments to Uncrustify, and added a new service.

### PR DESCRIPTION
**Pull request by jonah-williams**
Just a little clean up work to keep use of Uncrustify consistent between the different automator services and to increase the chances of these services working "out of the box". 

I found that I had to customize the services to change the hard coded paths to Uncrustify and Xcode before I could use them. For my own use I also added a `-c ~/path/to/uncrustify_obj_c.cfg` argument to all the Uncrustify calls but did not include it in these commits as I think it better to rely on the default config unless users choose to specify their own.

I also added a new "Uncrustify Modified Documents" service which I've found to be more useful and reliable than the "Open" and "Current Document" services. Xcode seems to consider many source files to be "open" and I haven't been able to find a reliable way to identify which one of them is actually currently visible or has focus. Instead I opted to format all open and modified files which I think strikes a decent balance between cleaning up everything and not introducing unexpected changes in otherwise untouched files.
In order to avoid the "revert" alert I replace the file contents in the add via AppleScript rather than replacing the file on disk. This avoid that annoying dialog box but iterating through source files in AppleScript with multiple calls to Uncrustify is rather slow when Xcode has many files open.

The commit messages are hopefully informative and you should be able to cherry pick any of these commits if you don't want to accept all of them.

### CODE REVIEW

**Comment by tonyarnold** [comment]
This looks like some well needed changes, Jonah — thanks! I've actually stopped using the "Current" and "Open" document services — as you said, they don't work consistently due to Xcode 4's oddball interpretation of the frontmost source document. I'll look at merging your changes in tomorrow :)

**Comment by tonyarnold** [comment]
OK, it's all merged. I need to think a little about how best to approach this in future — I'm kind of hoping someone will reverse engineer the plugin format.

**Comment by jonah-williams** [comment]
Great, thanks. Hopefully that wasn't too painful to merge. It's a shame those .wflow files contain user specific settings like window positions so it's a hassle to submit a minimal pull request.

**Comment by tonyarnold** [comment]
Not at all Jonah — I'd really like to find a better way to do this. Under Xcode 3, the scripts menu was speedy — services seem so slow in comparison. Thanks for your changes!

On 11/03/2011, at 15:19 PM, jonah-carbonfive wrote:

> Great, thanks. Hopefully that wasn't too painful to merge. It's a shame those .wflow files contain user specific settings like window positions so it's a hassle to submit a minimal pull request.
> 
> https://github.com/tonyarnold/Xcode-4-Uncrustify-Automator-Services/pull/2#issuecomment-859386

---

Tony Arnold
http://thecocoabots.com/

**Pull request closed without merging**
